//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperGate.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaperGate.Web.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود نامعتبر است!.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما حذف شده است.
        /// </summary>
        public static string AccountHasBeenDeleted {
            get {
                return ResourceManager.GetString("AccountHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به خانه.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string contactUs_Email {
            get {
                return ResourceManager.GetString("contactUs_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string contactUs_Message {
            get {
                return ResourceManager.GetString("contactUs_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست های اخیر.
        /// </summary>
        public static string contactUs_RecentPublications {
            get {
                return ResourceManager.GetString("contactUs_RecentPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string contactUs_Send {
            get {
                return ResourceManager.GetString("contactUs_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شما.
        /// </summary>
        public static string contactUs_YourName {
            get {
                return ResourceManager.GetString("contactUs_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راه های ارتباطی.
        /// </summary>
        public static string ContactWays {
            get {
                return ResourceManager.GetString("ContactWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string header_AboutUs {
            get {
                return ResourceManager.GetString("header_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string header_ContactUs {
            get {
                return ResourceManager.GetString("header_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string header_Home {
            get {
                return ResourceManager.GetString("header_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string header_Login {
            get {
                return ResourceManager.GetString("header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string header_Logout {
            get {
                return ResourceManager.GetString("header_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کاربری.
        /// </summary>
        public static string header_Panel {
            get {
                return ResourceManager.GetString("header_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه مقالات.
        /// </summary>
        public static string header_PaperGate {
            get {
                return ResourceManager.GetString("header_PaperGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت وارد شدید..
        /// </summary>
        public static string LoggedInSuccessfully {
            get {
                return ResourceManager.GetString("LoggedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت  خارج شدید.
        /// </summary>
        public static string LoggedOutSuccessfully {
            get {
                return ResourceManager.GetString("LoggedOutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به پنل کاربری.
        /// </summary>
        public static string Login_header {
            get {
                return ResourceManager.GetString("Login_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to می‌خواهید خارج شوید؟.
        /// </summary>
        public static string Logout_Message {
            get {
                return ResourceManager.GetString("Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این صفحه دسترسی ندارید.
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده همه.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
    }
}
